# Generated by Django 3.0.2 on 2021-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=20)),
                ('transact_date', models.DateField()),
                ('pallet', models.CharField(max_length=20)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('box_qty', models.FloatField(blank=True, null=True)),
                ('pallet_qty', models.FloatField(null=True)),
                ('bbd', models.DateField(null=True)),
                ('pickup_by', models.CharField(choices=[('NA', 'NA'), ('CTN', 'OUT'), ('PACK', 'PACK')], default='CTN', max_length=20)),
                ('memo', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'CK Stock Transaction',
                'verbose_name_plural': 'CK Stock Transactions',
            },
        ),
    ]
