# Generated by Django 3.0.2 on 2021-02-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenus', '0002_ckstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckstock',
            name='memo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ckstock',
            name='pickup_by',
            field=models.CharField(choices=[('NA', 'N/A'), ('CTN', 'OUT'), ('PACK', 'PACK')], default='CTN', max_length=20),
        ),
    ]
