# Generated by Django 3.0.2 on 2020-01-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('end_stock_day', models.DateField()),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('usage_month', models.DateField()),
                ('monthly_usage', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotUsedProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_code', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_code', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('inward', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('pickup_qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=300)),
            ],
        ),
    ]
