# Generated by Django 3.0.2 on 2020-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aDailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('inward', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Daily Stock',
                'verbose_name_plural': 'Daily Stocks',
            },
        ),
        migrations.CreateModel(
            name='aDailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('pickup_qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Daily Usage',
                'verbose_name_plural': 'Daily Usages',
            },
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('end_stock_day', models.DateField()),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Main Aggregated Stock',
                'verbose_name_plural': 'Main Aggregated Stocks',
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('usage_month', models.DateField()),
                ('monthly_usage', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Main Monthly Usage',
                'verbose_name_plural': 'Main Monthly Usages',
            },
        ),
        migrations.CreateModel(
            name='NoodleUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('customer', models.CharField(max_length=50, null=True)),
                ('sf_code', models.CharField(max_length=20, null=True)),
                ('simple_name', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Noodle Product Usage',
                'verbose_name_plural': 'Noodle Product Usages',
            },
        ),
        migrations.CreateModel(
            name='NotUsedProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_code', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_code', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('inward', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Main Stock',
                'verbose_name_plural': 'Main Stocks',
            },
        ),
        migrations.CreateModel(
            name='StorageTransactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_date', models.DateField()),
                ('transact_time', models.TimeField()),
                ('storage_loc', models.CharField(choices=[('LW', 'Lucky Winner'), ('OS', 'OSP'), ('HS', 'Haison'), ('HE', 'Hellman'), ('HX', 'HerbX')], default='LW', max_length=10)),
                ('transact_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=20)),
                ('total_pallet_before_transaction', models.FloatField(null=True)),
                ('pallet_qty', models.FloatField(null=True)),
                ('total_pallet_after_transaction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Storage Transaction Log',
                'verbose_name_plural': 'Storage Transaction Logs',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('pickup_qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Main Usage',
                'verbose_name_plural': 'Main Usages',
            },
        ),
    ]
