# Generated by Django 3.0.2 on 2020-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
