# Generated by Django 3.0.2 on 2020-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='storage_loc',
            field=models.CharField(choices=[('LW', 'Lucky Winner'), ('OS', 'OSP'), ('HS', 'Haison'), ('HE', 'Hellman'), ('HX', 'HubX')], default='LW', max_length=10),
        ),
    ]
