# Generated by Django 3.0.2 on 2020-10-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200827_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='adailyusage',
            name='cust_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='cust_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='noodleusage',
            name='customer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='storage_loc',
            field=models.CharField(choices=[('LW', 'Lucky Winner'), ('LW(D)', 'Lucky Winner (Dry)'), ('OS', 'OSP'), ('HS', 'Haison'), ('HE', 'Hellman'), ('HX', 'HubX')], default='LW', max_length=10),
        ),
    ]
