# Generated by Django 3.0.2 on 2020-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='origin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_name_jpn',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
