# Generated by Django 3.0.2 on 2020-03-01 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200301_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_name_jpn',
            new_name='product_name_jp',
        ),
    ]
