# Generated by Django 3.0.2 on 2020-04-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200301_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='origin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='product_name_jp',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
