# Generated by Django 3.0.2 on 2020-10-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201012_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoStockItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_code', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('product_spec', models.CharField(max_length=300, null=True)),
                ('container_name', models.CharField(max_length=50, null=True)),
                ('container_eta', models.DateField()),
                ('container_status', models.CharField(choices=[('normal', 'Normal'), ('D1', 'Delay 1'), ('D2', 'Delay 2'), ('D3', 'Delay 3'), ('D4', 'Delay 4'), ('D5', 'Delay 5'), ('D6', 'Delay 6')], default='controlling', max_length=30)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('stock_status', models.CharField(choices=[('closed', 'Closed'), ('nostock', 'No Stock'), ('controlling', 'Controlling')], default='controlling', max_length=30)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'No Stock Item',
                'verbose_name_plural': 'No Stock Items',
            },
        ),
    ]
