# Generated by Django 3.0.2 on 2020-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200415_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('inward', models.DateField(null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('new_balance', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('bbd', models.DateField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('pickup_qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=10, null=True)),
                ('product_name_jp', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
