# Generated by Django 3.0.2 on 2020-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20201013_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetransactlog',
            name='box_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nostockitems',
            name='container_eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nostockitems',
            name='container_name',
            field=models.CharField(blank=True, choices=[('COF', 'COF'), ('EEL', 'EEL'), ('FO', 'FO'), ('GN', 'GN'), ('Gyoren', 'Gyoren'), ('ITABASHI', 'ITABASHI'), ('LUF', 'LUF'), ('NW', 'NW'), ('OIL', 'OIL'), ('QP', 'QP'), ('STI', 'STI'), ('TEP', 'TEP'), ('TWIN', 'TWIN'), ('VFK', 'VFK'), ('YamasaFRZ', 'YamasaFRZ'), ('YM', 'YM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nostockitems',
            name='container_status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('D1', 'Delay 1'), ('D2', 'Delay 2'), ('D3', 'Delay 3'), ('D4', 'Delay 4'), ('D5', 'Delay 5'), ('D6', 'Delay 6')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nostockitems',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nostockitems',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('closed', 'Closed'), ('nostock', 'No Stock'), ('controlling', 'Controlling')], max_length=30, null=True),
        ),
    ]
