# Generated by Django 3.0.2 on 2020-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200519_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetransactlog',
            name='total_pallet_before_transaction',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='storage_loc',
            field=models.CharField(choices=[('LW', 'Lucky Winner'), ('OS', 'OSP'), ('HS', 'Haison'), ('HE', 'Hellman')], default='LW', max_length=10),
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='transact_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=20),
        ),
    ]
