# Generated by Django 3.0.2 on 2020-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200520_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePalletQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_loc', models.CharField(max_length=10)),
                ('total_pallet_qty', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Storage Pallet QTY',
                'verbose_name_plural': 'Storage Pallet QTYs',
            },
        ),
    ]
