# Generated by Django 3.0.2 on 2020-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storagepalletqty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoragePalletQty',
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='total_pallet_after_transaction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
