# Generated by Django 3.0.2 on 2020-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200521_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoodleUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('customer', models.CharField(max_length=50, null=True)),
                ('sf_code', models.CharField(max_length=20, null=True)),
                ('simple_name', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Noodle Product Usage',
                'verbose_name_plural': 'Noodle Product Usages',
            },
        ),
        migrations.AlterField(
            model_name='storagetransactlog',
            name='storage_loc',
            field=models.CharField(choices=[('LW', 'Lucky Winner'), ('OS', 'OSP'), ('HS', 'Haison'), ('HE', 'Hellman'), ('HX', 'HerbX')], default='LW', max_length=10),
        ),
    ]
