# Generated by Django 3.0.2 on 2020-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('product_type', models.CharField(max_length=10, null=True)),
                ('customer', models.CharField(max_length=10, null=True)),
                ('sf_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('qty', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20)),
                ('arrival_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Dispatched product',
                'verbose_name_plural': 'Dispatched products',
            },
        ),
    ]
