# Generated by Django 3.0.2 on 2020-04-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
    ]
