# Generated by Django 3.0.2 on 2020-05-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushi_train', '0002_auto_20200412_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packinglist',
            options={'verbose_name': 'Dispatched product', 'verbose_name_plural': 'Dispatched products'},
        ),
    ]
