# Generated by Django 3.0.2 on 2020-01-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, null=True)),
                ('sales_date', models.DateField()),
                ('product_code', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('product_spec', models.CharField(max_length=300, null=True)),
                ('product_unit', models.CharField(max_length=20)),
                ('product_cost', models.FloatField(null=True)),
                ('product_price', models.FloatField(null=True)),
                ('sales_qty', models.FloatField(null=True)),
            ],
        ),
    ]
