# Generated by Django 3.0.2 on 2020-05-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'SF Sale', 'verbose_name_plural': 'SF Sales'},
        ),
    ]
